openapi: 3.0.0

paths:
  /dojo-subscriptions:
    get:
      tags:
        - subscription
      description: Gets a list of dojos the user is subscribed to
      summary: Gets a list of dojo the user is subscribed to
      operationId: getSubscriptions
      parameters:
        - in: query
          name: userId
          description: Filter by user id
          schema:
            type: string
        - in: query
          name: dojoId
          description: Filter by dojo id
          schema:
            type: string
        - $ref: 'core.yaml#/components/parameters/page'
        - $ref: 'core.yaml#/components/parameters/size'
      responses:
        '200':
            description: Successful operation
            content:
              application/hal+json:
                schema:
                  $ref: '#/components/schemas/SubscriptionList'
        '404':
          $ref: 'core.yaml#/components/responses/NotFoundError'
        default:
          $ref: 'core.yaml#/components/responses/DefaultError'

    post:
      tags:
        - subscription
      description: Subscribes a user to the given dojo.
      summary: Subscribes a user to the given dojo
      operationId: subscribe
      requestBody:
        $ref: '#/components/requestBodies/PostSubscriptionBody'
      responses:
        '201':
          description: Successfully subscribed
        '400':
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SubscribeError'
        '404':
          $ref: 'core.yaml#/components/responses/NotFoundError'
        default:
          $ref: 'core.yaml#/components/responses/DefaultError'

  /dojo-subscriptions/{id}:
    delete:
      tags:
        - subscription
      description: Unsubscribes a user from the given dojo
      summary: Unsubscribes a user from the given dojo
      operationId: unsubscribe
      parameters:
        - $ref: 'core.yaml#/components/parameters/pathId'
      responses:
        '204':
          description: Successfully unsubscribed
        '404':
          $ref: 'core.yaml#/components/responses/NotFoundError'
        default:
          $ref: 'core.yaml#/components/responses/DefaultError'

components:
  requestBodies:
    PostSubscriptionBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            required:
              - userId
              - dojoId
            properties:
              userId:
                type: string
                description: ID of user who is subscribing
              dojoId:
                type: string
                description: ID of dojo that is suscribed to

  schemas:
    Subscription:
      type: object
      required:
        - id
        - _links
      properties:
        id:
          type: string
        _links:
          type: object
          properties:
            self:
              $ref: 'core.yaml#/components/schemas/LinkObject'
            dojo:
              $ref: 'core.yaml#/components/schemas/LinkObject'
            user:
              $ref: 'core.yaml#/components/schemas/LinkObject'
            subscriptions:
              $ref: 'core.yaml#/components/schemas/LinkObject'

    SubscriptionList:
      type: object
      required:
        - _embedded
        - _links
      properties:
        _embedded:
          type: object
          required:
            - subscriptions
          properties:
            subscriptions:
              type: array
              items:
                $ref: '#/components/schemas/Subscription'
            count:
                $ref: 'core.yaml#/components/schemas/Count'
        _links:
          type: object
          required:
            - self
          properties:
            self:
              $ref: 'core.yaml#/components/schemas/LinkObject'
            post:
              $ref: 'core.yaml#/components/schemas/LinkObject'
            root:
              $ref: 'core.yaml#/components/schemas/LinkObject'
            next:
              $ref: 'core.yaml#/components/schemas/LinkObject'
            prev:
              $ref: 'core.yaml#/components/schemas/LinkObject'
            first:
              $ref: 'core.yaml#/components/schemas/LinkObject'
            last:
              $ref: 'core.yaml#/components/schemas/LinkObject'
        _templates:
          type: object
          properties:
            post:
              $ref: 'core.yaml#/components/schemas/FormTemplate'

    SubscribeError:
      allOf:
        - $ref: 'core.yaml#/components/schemas/Error'
        - description: Error that specifies how the fields should be filled when filled in the wrong manner
          type: object
          properties:
            fieldErrors:
              type: object
              properties:
                userId:
                  type: string
                dojoId:
                  type: string
